### ISSUE TITLE
Any chance of integration with the Job DSL?

### ISSUE THREAD

**Issue by Nuxij** [jenkinsci/build-time-blame-plugin#12]
https://github.com/jenkinsci/job-dsl-plugin

I'd really love to see some options in the DSL for configuring my regex patterns and labels! 👍

**Comment by LTegtmeier** [comment]
That would be tricky. The regex patterns and labels aren't stored in the job's config.xml where the Job DSL Plugin operates. They are stored in a separate file. 
I did it this way because it is not one of the regular parts of a Job Config. It is an extra tool for analyzing the output of existing builds and does not affect the job at execution time.

It may have changed since I last looked at this. But, at the time the Job DSL Plugin could not affect anything outside the config.xml. I can try to look into that. But, a Pull Request to that effect would get your change in much faster. 😉

**Comment by LTegtmeier** [comment]
I don't think that scripting the configuration via Job DSL or Jenkins 2.0 Pipelines is very helpful and so don't plan to work on this.
