### ISSUE TITLE
Required Jenkins version differs in doc and reality

### ISSUE THREAD

**Issue by karkusviktor** [jenkinsci/build-time-blame-plugin#31]
**Describe the bug**
The pom.xml includes 2.235.2 rather than the one mentioned 2.164.1.

https://github.com/jenkinsci/build-time-blame-plugin/blob/1f2eaea184299de3c9925cf1f1af831ba115b7ba/pom.xml#L20

https://github.com/jenkinsci/build-time-blame-plugin/blob/1f2eaea184299de3c9925cf1f1af831ba115b7ba/README.md#L6

I think it would be better to set it back to 2.164.1 if it doesn't break anything, because I think it should shrink unnecessary the supported versions.

**Comment by LTegtmeier** [comment]
Does it show a warning or error if someone tries to install the plugin on a 2.164.1 Jenkins master? 

The plugin hasn't started using any new features introduced after 2.164.1. So, I would expect it to still work there. If there is actually a problem running in 2.164.1, I'll update the pom.xml to increase the support. 

But, it is my understanding that the version in the pom.xml only controls the version that is used for building the project. Unfortunately, it's not convenient to test against a range of versions in each build.

Jenkins can introduce breaking changes to plugins in the 2.x line such as when they updated CORS rules which is one reason to test against a newer version. The `>` in the version range is important too since it implicitly promises that the plugin deals with any issues in newer versions.

I don't know of any particular problems with later versions of Jenkins. So, if you want to submit a PR to go back to 2.164.1 in the pom.xml, I'd approve it. I just don't see the value in changing it unless it has an impact beyond what version the tests build with.

**Comment by karkusviktor** [comment]
I don't know how the version number in the pom.xml affects the required version I just saw that on the plugin site it refers that version as minimum:
![build-time-2](https://user-images.githubusercontent.com/14263851/94692889-5fc69f80-0333-11eb-815e-1b8d1e2fa579.png)
Also when I list the availiable plugins on an older Jenkins it just shows up the last "compatible" one, so 1.2.1:
![build-time-1](https://user-images.githubusercontent.com/14263851/94693038-88e73000-0333-11eb-877c-82da30f5cd11.png)
Also I couldn't manually install it, it complains about the same version number issue, idk if it's possible to turn it off:
![build-time-3](https://user-images.githubusercontent.com/14263851/94693140-a4523b00-0333-11eb-829c-1a4b1f8e494e.png)

**Comment by LTegtmeier** [comment]
I was not aware that Jenkins enforced that restriction and treated that as a minimum version. #32 will address this.

I would still recommend you update your master as Jenkins is always putting out security patches but, I know that can have unexpected trouble.

**Comment by LTegtmeier** [comment]
I have to switch machines to publish. I'll get to publishing 2.0.3 when I can.
